apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "apbsrest.fullname" . }}-proxy
  labels:
    app: {{ template "apbsrest.name" . }}
    chart: {{ template "apbsrest.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    service: proxy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "apbsrest.name" . }}
      release: {{ .Release.Name }}
      service: proxy
  template:
    metadata:
      labels:
        app: {{ template "apbsrest.name" . }}
        release: {{ .Release.Name }}
        service: proxy
    spec:
      serviceAccountName: {{ template "apbsrest.fullname" . }}-proxy
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}"
          imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
          env:
          - name: FLASK_APP
            value: "main.py"
          - name: STORAGE_HOST
            value: http://{{ template "apbsrest.fullname" . }}-storage.{{ .Release.Namespace }}
          - name: TESK_HOST
            value: http://{{ template "apbsrest.fullname" . }}-tesk
          - name: UI_HOST
            value: http://{{ template "apbsrest.fullname" . }}
          - name: FLASK_RUN_PORT
            value: "5007"
          - name: IMAGE_PULL_POLICY
            value: {{ .Values.proxy.env.workloadPullPolicy }}
          - name: VOLCANO_NAMESPACE
            value: {{ default .Release.Namespace .Values.proxy.env.volcanoNamespace }}
          - name: APBS_JOB_IMAGE_REPO
            value: {{ .Values.proxy.env.apbsExecImageRepo | quote }}
          - name: APBS_JOB_IMAGE_TAG
            value: {{ .Values.proxy.env.apbsExecImageTag | quote }}
          - name: PDB2PQR_JOB_IMAGE_REPO
            value: {{ .Values.proxy.env.pdb2pqrExecImageRepo | quote }}
          - name: PDB2PQR_JOB_IMAGE_TAG
            value: {{ .Values.proxy.env.pdb2pqrExecImageTag | quote }}
          - name: DOWNLOADER_JOB_IMAGE_REPO
            value: {{ .Values.proxy.env.downloaderImageRepo | quote }}
          - name: DOWNLOADER_JOB_IMAGE_TAG
            value: {{ .Values.proxy.env.downloaderImageTag | quote }}
          - name: UPLOADER_JOB_IMAGE_REPO
            value: {{ .Values.proxy.env.uploaderImageRepo | quote }}
          - name: UPLOADER_JOB_IMAGE_TAG
            value: {{ .Values.proxy.env.uploaderImageTag | quote }}
          - name: APBS_JOB_MEM_LIMIT
            value: {{ .Values.proxy.env.apbsExecMemoryLimit }}
          - name: APBS_UPLOAD_MEM_LIMIT
            value: {{ .Values.proxy.env.apbsUploadMemoryLimit }}
          - name: PDB2PQR_JOB_MEM_LIMIT
            value: {{ .Values.proxy.env.pdb2pqrExecMemoryLimit }}
          - name: PDB2PQR_UPLOAD_MEM_LIMIT
            value: {{ .Values.proxy.env.pdb2pqrUploadMemoryLimit }}
          - name: GA_TRACKING_ID
            value: {{ .Values.common.env.googleAnalyticsId }}
          - name: GA_JOBID_INDEX
            value: {{ .Values.common.env.googleAnalyticsJobidIndex | quote }}
          ports:
            - name: http
              containerPort: 5007
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /check
              port: http
          readinessProbe:
            httpGet:
              path: /check
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
