apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "apbsrest.fullname" . }}-task
  labels:
    app: {{ template "apbsrest.name" . }}
    chart: {{ template "apbsrest.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    service: task
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "apbsrest.name" . }}
      release: {{ .Release.Name }}
      service: task
  template:
    metadata:
      labels:
        app: {{ template "apbsrest.name" . }}
        release: {{ .Release.Name }}
        service: task
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.task.image.repository }}:{{ .Values.task.image.tag }}"
          imagePullPolicy: {{ .Values.task.image.pullPolicy }}
          env:
          - name: FLASK_APP
            value: "main.py"
          - name: STORAGE_URL
            value: http://{{ template "apbsrest.fullname" . }}-storage/api/storage
          - name: STORAGE_HOST
            value: http://{{ template "apbsrest.fullname" . }}-storage
          - name: TMP_EXEC_HOST
            value: http://{{ template "apbsrest.fullname" . }}-proxy
          - name: FLASK_RUN_PORT
            value: "5004"
          ports:
            - name: http
              containerPort: 5004
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /check
              port: http
          readinessProbe:
            httpGet:
              path: /check
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
