FROM python:3.7
WORKDIR /app
COPY requirements.txt /app
RUN python -m pip install -r requirements.txt gunicorn==19.9.0

        # && rm .env
        # && ls -la
ENV STORAGE_CACHE_DIR="/app/.minio_cache" \
    MINIO_URL="localhost:9000" \
    MINIO_ACCESS_KEY="xxx" \
    MINIO_SECRET_KEY="yyyyyyyy" \
    MINIO_JOB_BUCKET="jobs" \
    FLASK_RUN_PORT="5001" \
    FLASK_RUN_HOST="0.0.0.0" \
    FLASK_DEBUG="1" \
    FLASK_APP="main.py"


COPY . ./

EXPOSE 5001
ENTRYPOINT [ "python" ]
CMD [ "main.py" ]
#ENTRYPOINT [ "flask" ]
#CMD [ "run" ]

#gunicorn fails on local
#ENTRYPOINT [ "gunicorn" ]
#CMD [ "-w", "4", "-b", "0.0.0.0:5001", "main:app" ]
